version: "3.8"
services: 
    webapp:
        build: .
        ports:
            - "8000:80"
        volumes: 
            - ./src:/var/www/html
        networks: 
            - php-net
        environment:
            - APP_KEY=SomeRandomStringToAddSecurity123
            - APP_ENV=development
            - APP_DEBUG=true
            - APACHE_RUN_USER=apache-www-volume
            - APACHE_RUN_GROUP=apache-www-volume

    db:
        image: mysql
        restart: always 
        ports: 
            - "3306:3306"
        volumes: 
            - ./src/private/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root 
        networks: 
            - php-net
        depends_on: 
            - webapp


networks:
    php-net: